-- EcoVision AI — Supabase PostgreSQL migration
-- Run this entire file once in Supabase Dashboard → SQL Editor.
-- The Streamlit server uses SUPABASE_SERVICE_ROLE_KEY and never uses SQLite.

create extension if not exists pgcrypto;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text not null unique,
    phone text default '',
    password_hash text not null,
    salt text not null,
    role text not null default 'citizen' check (role in ('citizen','officer')),
    ward text default '',
    address text default '',
    avatar_path text default '',
    security_question text default '',
    security_answer_hash text,
    reward_points integer not null default 0,
    is_active boolean not null default true,
    auth_provider text not null default 'email' check (auth_provider in ('email','google')),
    oauth_subject text,
    created_at timestamptz not null default now(),
    last_login timestamptz
);
create unique index if not exists uq_users_oauth_subject on public.users(oauth_subject) where oauth_subject is not null;
create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_created_at on public.users(created_at desc);

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    icon text,
    disposal_guide text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.complaints (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    category text not null,
    ai_predicted_category text,
    ai_confidence numeric,
    description text,
    ai_description text,
    priority text not null default 'Medium' check (priority in ('Low','Medium','High')),
    status text not null default 'Submitted',
    image_path text,
    latitude double precision,
    longitude double precision,
    ward text,
    address_text text,
    assigned_officer_id bigint references public.users(id) on delete set null,
    assigned_worker text,
    officer_notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resolved_at timestamptz
);
create index if not exists idx_complaints_user on public.complaints(user_id);
create index if not exists idx_complaints_status on public.complaints(status);
create index if not exists idx_complaints_ward on public.complaints(ward);
create index if not exists idx_complaints_created_at on public.complaints(created_at desc);

create table if not exists public.complaint_timeline (
    id bigint generated by default as identity primary key,
    complaint_id bigint not null references public.complaints(id) on delete cascade,
    status text not null,
    note text,
    changed_by bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.rewards (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    points integer not null,
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.chat_history (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete cascade,
    session_id text not null,
    role text not null check (role in ('user','assistant')),
    message text not null,
    language text default 'en',
    created_at timestamptz not null default now()
);
create index if not exists idx_chat_user_session on public.chat_history(user_id, session_id, created_at);

create table if not exists public.recycling_centres (
    id bigint generated by default as identity primary key,
    name text not null,
    type text,
    address text,
    ward text,
    latitude double precision,
    longitude double precision,
    contact text,
    materials_accepted text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.carbon_records (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    transport_kg numeric default 0,
    electricity_kg numeric default 0,
    plastic_kg numeric default 0,
    water_kg numeric default 0,
    food_kg numeric default 0,
    waste_kg numeric default 0,
    total_score numeric,
    created_at timestamptz not null default now()
);

create table if not exists public.login_attempts (
    id bigint generated by default as identity primary key,
    email text not null,
    success boolean not null,
    ip_hint text,
    created_at timestamptz not null default now()
);
create index if not exists idx_login_email on public.login_attempts(email, created_at desc);

create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    action text not null,
    details text,
    created_at timestamptz not null default now()
);

-- Separate admin identity, deliberately independent of public users.
create table if not exists public.admin_users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    first_name text not null,
    last_name text not null,
    is_super_admin boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    last_login_at timestamptz
);
create index if not exists idx_admin_users_email on public.admin_users(lower(email));

-- Keep the database API inaccessible to anonymous browser clients.
-- The Streamlit server uses the service-role key and therefore bypasses RLS.
alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.complaints enable row level security;
alter table public.complaint_timeline enable row level security;
alter table public.rewards enable row level security;
alter table public.chat_history enable row level security;
alter table public.recycling_centres enable row level security;
alter table public.carbon_records enable row level security;
alter table public.login_attempts enable row level security;
alter table public.audit_log enable row level security;
alter table public.admin_users enable row level security;

-- Supabase Storage for complaint photos/videos. Actual metadata/path is stored
-- in public.complaints.image_path.
insert into storage.buckets (id, name, public)
values ('ecovision-media', 'ecovision-media', false)
on conflict (id) do nothing;

-- Seed reference categories.
insert into public.categories (name, description, icon, disposal_guide) values
('Plastic','Plastic bottles, bags, wrappers, containers','🧴','Rinse and place in dry waste; use an authorized recycler for bulk plastic.'),
('Organic','Food scraps, garden waste and biodegradable matter','🍂','Compost at home or place in the wet-waste stream.'),
('Paper','Newspaper, cardboard, cartons and office paper','📄','Keep paper dry and send it to an authorized recycler.'),
('Glass','Bottles, jars and glass containers','🍾','Keep glass separate and send it to an authorized recycler.'),
('Metal','Cans, tins, aluminium and scrap metal','🥫','Keep dry and send to an authorized scrap dealer or recycler.'),
('Mixed','Mixed or non-segregated household waste','🗑️','Separate wet, dry, hazardous and e-waste before disposal.'),
('E-Waste','Electronics, chargers, batteries and cables','🔋','Never put e-waste in household bins; use an authorized e-waste centre.'),
('Biomedical','Sanitary and biomedical waste','🧪','Keep isolated and follow municipal/healthcare disposal guidance.'),
('Construction','Concrete, rubble, tiles and construction debris','🧱','Use an authorized construction-waste collection channel.')
on conflict (name) do nothing;

-- Optional bootstrap admin:
-- Prefer configuring ADMIN_EMAIL / ADMIN_PASSWORD in Streamlit Secrets.
-- The application will create the first admin automatically on first Admin Panel visit.
